### ISSUE TITLE
merge 6 methods into 3 methods (I can create a PR)

### ISSUE THREAD

**Issue by fzyzcjy** [CMU-Graphics/Scotty3D#11]
Hi thanks for the assignment! There are 6 methods in Skeleton Kinematics. However, they are actually 3 pairs:

* Joint::joint_to_bind vs Joint::joint_to_posed
* Skeleton::end_of vs Skeleton::posed_end_of
* Skeleton::joint_to_bind vs Skeleton::joint_to_posed

And the functionality are very similar for the two methods in one pair. Actually, IMHO, the *only* difference is whether to use `joint->pose` or treat pose as zero.

Thus, I propose that, we can happily merge each pair of 2 methods into 1 method with a bool argument. For example:

```
Mat4 Skeleton::joint_to_bind(const Joint* j) const {
    return Mat4::translate(base_pos) * j->joint_to_bind();
}
Mat4 Skeleton::joint_to_posed(const Joint* j) const {
    return Mat4::translate(base_pos) * j->joint_to_posed();
}
```

becomes

```
Mat4 Skeleton::joint_to_posed(const Joint* j, bool ignore_pose) const {
    return Mat4::translate(base_pos) * j->joint_to_posed(ignore_pose);
}
```

If welcomed, I can create a PR!

**Comment by TheNumbat** [comment]
This would make the code a bit clearer, but I think we would rather students consider the bind pose and posed transformations as entirely separate coordinate frames. Although in Scotty3D bind pose means zero joint angles, in general the bind pose can be chosen as any particular joint arrangement.

**Comment by fzyzcjy** [comment]
Thanks for the explanation!
