### ISSUE TITLE
UI scaling issue with "save changes" dialog box

### ISSUE THREAD

**Issue by ishantheperson** [CMU-Graphics/Scotty3D#12]
The dialog box is too small on a 4k screen. 
Steps to reproduce:

 1. Open Scotty3D
 2. Create a cube
 3. Try to close the window

![image](https://user-images.githubusercontent.com/1707565/110696591-1f036a00-81a0-11eb-88de-a8bd37c7ef5d.png)

**Comment by TheNumbat** [comment]
Should be fixed now, re-open if it's not.
