### ISSUE TITLE
Unable to render small spheres.

### ISSUE THREAD

**Issue by pachiko** [CMU-Graphics/Scotty3D#2]
Hi, I am unable to render a small Lambertian sphere (radius=0.25) with rectangle lights above it (size=(0.2,0.2)). It works fine however, if I disable spherical mesh and use triangular mesh, or if I use the default sizes of 1 for both light and sphere. Viewing the normals of the sphere is correct, and the rays do indeed intersect the small sphere when I hardcode ray misses with a green spectrum (ie only the sphere is black). I think it has something to do with cos_theta < 0. Currently I'm only at Task 4, without shadow raysand setting the initial radiance_out to 0.f.

I've attached a screenshot and the dae file. Hope you can shed light on this ! 

[test.zip](https://github.com/CMU-Graphics/Scotty3D/files/5692569/test.zip)

![Capture](https://user-images.githubusercontent.com/42316301/102155570-c4b37f80-3eb6-11eb-9041-4c983e20c1bc.PNG)

**Comment by pachiko** [comment]
@TheNumbat  Hope you can give some pointers on this. I noticed if I move the light a little higher it will render parts of the sphere.

**Comment by TheNumbat** [comment]
Not really sure what the problem is given the provided information. However, if it works with the triangle mesh sphere, I'd guess this is an issue with your sphere intersection implementation. Check if your hit positions and normals make sense with different radii (not just whether the ray hit).
