### ISSUE TITLE
BSDF_Lambertian evaluate

### ISSUE THREAD

**Issue by ruiwng** [CMU-Graphics/Scotty3D#20]
In the Lambertian evaluate function in file bsdf.cpp, to compute the ratio of reflected radiance when light from in_dir is reflected through out_dir, I think the correct approach should be:
```c++
albedo * cos(theta) / PI_F
```
 rather than:
```c++
albedo * cos(theta)
```
the PI_F term is here to keep energy conversed. However, when I use the second method, I get the same result as the reference results in [path tracing](https://cmu-graphics.github.io/Scotty3D/pathtracer/path_tracing), when I change it to the first method, the rendering result is a little darker than the reference result. So I want to make sure that the reference result is rendered with or without the PI_F term. This is the result I rendered with 1024 samples per pixel:
![1024spp](https://user-images.githubusercontent.com/10192495/166209568-4a833cee-a688-4f07-8a30-626bc162669b.png)

**Comment by TheNumbat** [comment]
The albedo is already divided by pi here: [https://github.com/CMU-Graphics/Scotty3D/blob/main/src/rays/bsdf.h#L26](https://github.com/CMU-Graphics/Scotty3D/blob/main/src/rays/bsdf.h#L26)

So, the reference result uses `albedo * cos(theta)` for the Lambertian evaluate.

**Comment by ruiwng** [comment]
I think it's a bit ambiguous to handle it this way, after all `albedo` is not `albedo divided by pi`.

**Comment by TheNumbat** [comment]
Fair - I'll add that to the documentation.

**Comment by ruiwng** [comment]
That's very fine.
