### ISSUE TITLE
Should Spectrum BSDF_Mirror::evaluate be changed?

### ISSUE THREAD

**Issue by pachiko** [CMU-Graphics/Scotty3D#3]
Hi, I am confused by the aforementioned method. Should it always return 0? But the docs said it should be implemented..

**Comment by TheNumbat** [comment]
You could check if the input/output directions represent a perfect reflection and return the proper attenuation, but given that evaluate is only called with directions sampled from direct lighting, there is (theoretically) no chance we ever hit a perfect reflection pair. Hence it is fine to have it always return 0.
