### ISSUE TITLE
CDF for conditional distribution in importance sampling

### ISSUE THREAD

**Issue by pachiko** [CMU-Graphics/Scotty3D#5]
Hi, I noticed that for Sphere::Image, it only has the pdf and cdf members, which are for the joint p(theta, phi) and the cumulative, marginal P(theta). Is the conditional p(phi | theta) supposed to be calculated in Sphere::Image::sample(float &out_pdf)? Wouldn't that be slow, since there needs to be a for-loop to iterate over the columns in the selected row, and divide each p(theta=y, phi) by the sampled marginal p(theta=y)?

**Comment by allai5** [comment]
It should be fine. Alternatively, instead of reducing the problem to sampling from two 1D distributions, you can define the cdf vector across the entire image and then just perform inversion sampling on that.
